- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: prepare
  vars:
    service_defaults:
      name: traefik
      version: "latest"
      port: 8080
      traefik: true
      external: true
      watchtower: true
      autoheal: true
      internal_ip_ranges: []
      subdirs:
        - "dynamic"

- name: Copy static config traefik.yml
  template:
    src: traefik.yml.j2
    dest: '{{ service_cfg.directory }}/traefik.yml'
    owner: '{{ service_cfg.owner }}'
    group: "{{ service_cfg.group }}"
  tags: [ always, started, restarted, recreated ]

- name: Copy dynamic config files
  copy:
    src: "{{ item }}"
    dest: '{{ service_cfg.directory }}/dynamic/{{ item }}'
    owner: '{{ service_cfg.owner }}'
    group: "{{ service_cfg.group }}"
  tags: [ always, started, restarted, recreated ]
  with_items:
    - tls-options.yml
    - https-redirect-all.yml

- name: Copy rules/middlewares.yml
  template:
    src: middlewares.yml.j2
    dest: '{{ service_cfg.directory }}/dynamic/middlewares.yml'
    owner: '{{ service_cfg.owner }}'
    group: "{{ service_cfg.group }}"
  tags: [ always, started, restarted, recreated ]

- name: ensure acme.json exists
  copy:
    content: ""
    dest: '{{ service_cfg.directory }}/acme.json'
    force: no
    group: "{{ service_cfg.group }}"
    owner: "{{ service_cfg.owner }}"
    mode: 0600
  tags: [ always, started, restarted, recreated ]

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: deploy_docker
